export const LANG_DISPLAY: Record<string, string> = {
  bash: 'Bash',
  c: 'C',
  cc: 'C++',
  'cc.cc98': 'C++98',
  'cc.cc98o2': 'C++98(O2)',
  'cc.cc11': 'C++11',
  'cc.cc11o2': 'C++11(O2)',
  'cc.cc14': 'C++14',
  'cc.cc14o2': 'C++14(O2)',
  'cc.cc17': 'C++17',
  'cc.cc17o2': 'C++17(O2)',
  'cc.cc20': 'C++20',
  'cc.cc20o2': 'C++20(O2)',
  cs: 'C#',
  go: 'Golang',
  hs: 'Haskell',
  java: 'Java',
  js: 'NodeJS',
  kt: 'Kotlin',
  'kt.jvm': 'Kotlin/JVM',
  pas: 'Pascal',
  php: 'PHP',
  py: 'Python',
  'py.py2': 'Python 2',
  'py.py3': 'Python 3',
  'py.pypy3': 'PyPy3',
  r: 'R',
  rb: 'Ruby',
  rs: 'Rust',
  ts: 'TypeScript',
};

export function getLangDisplay(lang: string): string {
  return LANG_DISPLAY[lang] || lang;
}
